### ISSUE TITLE
Typecho后台编辑器按钮问题

### ISSUE THREAD

**Issue by mokehow** [metowolf/Meting-Typecho-Plugin#1]
您好，挺棒的插件，可是后台按钮并没有啊？手机上的页面很多按钮会不显示。
直接在编辑器输入：

' [Meting autoplay="false" mode="random" theme="blue"]
[Music server="netease" id="32507038" type="song"/]
[Music server="netease" id="436355188" type="song"/]
[Music server="netease" id="440241144" type="song"/]
[/Meting] '

就直接显示代码了，是什么问题？怪我的主题？

**Comment by mokehow** [comment]
不是，没有那个   '  '   包围的

**Comment by metowolf** [comment]
编辑器按钮已经改为一个头戴耳机的图标，在按钮的最右边
关于你的这段代码，我测试过是可以正常解析的，不排除是主题问题，可以提供一下主题我进行适配

**Comment by mokehow** [comment]
抱歉<(_ _)>
忘记开启插件了……
可以的，谢谢(*°∀°)=3
http://www.moccoo.cn/index.php/archives/4/

**Comment by metowolf** [comment]
:joy: 我还以为有什么蜜汁 BUG

**Comment by liwanglin12** [comment]
作者：我查了半个小时的 BUG 🌚

**Comment by mokehow** [comment]
23333   尴尬了。辛苦作者了😂😂😂
作者：被白痴坑了……怎么遇上这种白痴(=_=)
