### ISSUE TITLE
定后，文字编辑页面无相关信息显示

### ISSUE THREAD

**Issue by Sun163** [metowolf/Meting-Typecho-Plugin#10]
你好，请问插入音乐——确定后，文字编辑页面无相关信息显示，发表后也不见播放器显示出来是什么问题

**Comment by metowolf** [comment]
应该是 Meting 组件出现了错误，检查你的环境是否为 PHP5.4+，更新插件到最新版本重试一下

**Comment by Sun163** [comment]
PHP 是  5.5 版本的
Typecho 我又全新安装,只有Meting这个插件

**Comment by metowolf** [comment]
服务器/主机环境是什么，如果方便的话请提供一个具体的 URL，我可以去排查

**Comment by Sun163** [comment]
Linux + Apache/2.4.17 +PHP5.5.30
---------------------------------------
http://lees21.com/lees
User: Tester Pw:654123

**Comment by Sun163** [comment]
和这个是一个问题
http://forum.typecho.org/viewtopic.php?f=6&t=9922&start=10#p38202

**Comment by metowolf** [comment]
可以尝试一下刚刚发布的 1.2.0 版本，如果还是不行，可以在插件中打开云解析

**Comment by Sun163** [comment]
打开打开云解析   直接放入代码  可以了 。  谢谢！幸苦了!
