### ISSUE TITLE
安装报错

### ISSUE THREAD

**Issue by loveofyou** [metowolf/Meting-Typecho-Plugin#2]
作者 您好 ，非常感谢您创造的这个插件，但是我在安装时出现了一些问题。
直接使用git clone下载项目到/usr/plugins，然后按照说明将Meting-Typecho-Plugin文件夹修改为Meting，
在插件管理页面内启用时提示：数据表建立失败，插件启用失败。错误号: HY000.

**Comment by loveofyou** [comment]
突然想起我使用的数据库模式为sqlite，是否是因为数据库的原因

**Comment by metowolf** [comment]
是的，目前还不支持 sqlite

**Comment by sunnyWu1104** [comment]
@loveofyou 您解决了这个问题了吗，我报的是1050，看了代码应该跟你的问题是一样的

**Comment by sunnyWu1104** [comment]
@metowolf @loveofyou 哇，知道问题了，我启用后又禁用，但是表已经建好了，再次启用就会报错，= =代码还没看，作者您是每次启用的时候都建表吗？

**Comment by sunnyWu1104** [comment]
@metowolf 看了您的代码，貌似是我不是通过禁用插件，而是直接删除插件文件导致的表没有删除，致使下一次安装插件启动的时候报错。尴尬~

**Comment by loveofyou** [comment]
准备自己看看修改一下代码去支持sqlite然后pullrequest，可惜最近一直没空～～

**Comment by metowolf** [comment]
#5 已经解决 SQLite 支持
