### ISSUE TITLE
不写入数据问题

### ISSUE THREAD

**Issue by farquer** [metowolf/Meting-Typecho-Plugin#3]
作者您好，我在typecho上使用的1.4版本，查看库中正确建立meting表，但是在markdown中点击音乐图表输入url确定后，页面无任何变化，发布文章之后也没有播放器，查看表中meting表还是空的。

**Comment by metowolf** [comment]
应该是 PHP 版本的问题，检查一下是否为 PHP 5.4+
告知一下服务器环境

**Comment by farquer** [comment]
是 5.4 的环境

**Comment by metowolf** [comment]
检查一下 php-mcrypt, php-curl 是否有安装

**Comment by farquer** [comment]
解决了 谢谢拉。
