### ISSUE TITLE
一切正常，但是选择歌曲发布文章后，并没有效果

### ISSUE THREAD

**Issue by sunnyWu1104** [metowolf/Meting-Typecho-Plugin#4]
我按您的顺序执行下来后
问题如上，并没有任何反应
ps：我是非原生的主题

**Comment by metowolf** [comment]
可以右键查看源代码，找到几个含有 MetingAPI 的链接，直接进入看看是否输出

**Comment by GuchengCN** [comment]
我的也是，直接显示代码[Meting]
[Music server="xiami" id="1769714468" type="song"/]
[/Meting]....
右键查看源代码没有MetingAPI的链接

**Comment by GuchengCN** [comment]
已经解决，是主题自带插件问题。但是网易云和虾米都不能正常播放，可能是api问题。

**Comment by GuchengCN** [comment]
然后我更新了1.0.5，虾米已经可以用了，网易云还不行。

**Comment by metowolf** [comment]
你试着访问 http://example.com/index.php/MetingAPI?site=netease&do=url&id=460476155
看是否报错

**Comment by fanghongxing** [comment]
为什么我添加音乐的时候编辑框没有任何反应？能够打开插入音乐的那个框，添加链接确定没有任何反应……

**Comment by fanghongxing** [comment]
竟然换个主机商就有可以了……囧！

**Comment by metowolf** [comment]
@fanghongxing 通常建议选择 PHP 5.6+ 的空间

**Comment by fanghongxing** [comment]
嗯嗯。知道啦！谢谢。

**Comment by sunnyWu1104** [comment]
作者，PHP5.5都不行吗？其他办法我都试过了，添加链接没反应，我看了楼上的小伙伴，只能改版本吗

**Comment by metowolf** [comment]
@sunnyWu1104 通常来讲是可以支持到 5.4 的，但不同的主机环境不同，建议尽量升级到最新版本再尝试
