### ISSUE TITLE
更新1.1.0的之后，刷新一遍就没有加载出来了。

### ISSUE THREAD

**Issue by fanghongxing** [metowolf/Meting-Typecho-Plugin#6]
RT！我检查了好几遍，不知道是什么原因？

**Comment by metowolf** [comment]
使用新版需要先禁用旧版
没有加载的话可以按 F12 查看 Console 的报错信息

**Comment by fanghongxing** [comment]
Uncaught TypeError: Cannot read property 'addEventListener' of null
    at Object.addEL (functions.js:3)
    at Object.show (functions.js:16)
    at functions.js:28
MetingAPI Failed to load resource: the server responded with a status of 500 (Internal Server Error)


就是这个~

**Comment by metowolf** [comment]
通常是 PHP 版本过低或者 Meting 库的问题，近期作了一些更新，可以下载最新版重试一下
