### ISSUE TITLE
输入歌单点确定后没反应

### ISSUE THREAD

**Issue by xau0at** [metowolf/Meting-Typecho-Plugin#7]
F12下看了一下 提示500错误，提示如下，（将域名换成了abc.com）

> synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.
send @ jquery.js?v=14.10.10:25
ajax @ jquery.js?v=14.10.10:25
(anonymous) @ editer.js?v=1.1.0:26
dispatch @ jquery.js?v=14.10.10:25
elemData.handle @ jquery.js?v=14.10.10:25
jquery.js?v=14.10.10:25 POST https://abc.com/MetingAPI?do=parse 500 (Internal Server Error)
send @ jquery.js?v=14.10.10:25
ajax @ jquery.js?v=14.10.10:25
(anonymous) @ editer.js?v=1.1.0:26
dispatch @ jquery.js?v=14.10.10:25
elemData.handle @ jquery.js?v=14.10.10:25
jquery.js?v=14.10.10:25 XHR finished loading: POST "https://abc.com/MetingAPI?do=parse".
send @ jquery.js?v=14.10.10:25
ajax @ jquery.js?v=14.10.10:25
(anonymous) @ editer.js?v=1.1.0:26
dispatch @ jquery.js?v=14.10.10:25
elemData.handle @ jquery.js?v=14.10.10:25``

**Comment by Nobiel** [comment]
我也遇到了同样的问题。

**Comment by xau0at** [comment]
@Nobiel 你是国外VPS吗？

**Comment by Nobiel** [comment]
@xau0at 是的，难道是因为海外ip无法访问？

**Comment by xau0at** [comment]
@Nobiel 看来应该是这个问题 API在海外无法调用

**Comment by Nobiel** [comment]
@xau0at 有没有替代品呢

**Comment by xau0at** [comment]
@Nobiel 不过我看https://binaryify.github.io/NeteaseCloudMusicApi/ 这个里面提到了海外使用的方法 不知道这和插件能参考@metowolf

**Comment by xau0at** [comment]
@Nobiel 已经找到解决办法了
https://github.com/metowolf/Meting/issues/15
这个issues最后一个回复 
确实是参考了我刚才发的NodeJS的解决办法

**Comment by Nobiel** [comment]
@xau0at Thanks.我试试。

**Comment by Nobiel** [comment]
@xau0at Thanks.你成功了吗？我试了一下还是不行。

**Comment by xau0at** [comment]
@Nobiel 我还没试 出差在外不方便

**Comment by D-Bood** [comment]
我是刚刚开始用typecho，然后下了这个试了一下
我的VPS在JP，直连是可以用的

**Comment by Nobiel** [comment]
@D-Bood 但是我发现Aplayer插件可以正常解析

**Comment by NeduTestLab** [comment]
我的启用插件之后，添加音乐没反应，console显示有一个错误http://www.abc.com/index.php/MetingAPI?do=musicjs&s=IiI=&d=W3sic2VydmVyIjoibmV0ZWFzZSIsImlkIjoiMjc0ODMxNjciLCJ0eXBlIjoic29uZyJ9XQ==&id=2 Failed to load resource: the server responded with a status of 500 (Internal Server Error)

域名使用abc.com代替

**Comment by metowolf** [comment]
500 错误是因为 Meting 库的原因，建议下载最新的版本，再重试。
如果还是不行，应该是 PHP 版本过低 (>=5.4) 或者部分扩展缺失 (openssl curl)
